# Autogenerated by pybind stub generator
# Do not manually edit
# To regenerate:
#   $ buck run //mapillary/opensfm/opensfm/src/dense:pydense_stubgen
# @generated
#
# Tip: Be sure to run this with the build mode you use for your project, e.g.,
# @//arvr/mode/linux/opt (or dev) in arvr.
#
# Ignore errors for [24] untyped generics.
# pyre-ignore-all-errors[24]

import numpy
from typing import *

__all__ = [
    "DepthmapCleaner",
    "DepthmapEstimator",
    "DepthmapFuser",
    "DepthmapPruner",
    "DSMRasterizer",
    "GPUDepthmapCleaner",
    "OpenMVSExporter",
    "StaticExtensionLoader",
]


class DepthmapCleaner:
    def __init__(self) -> None: ...

    def add_view(
        self,
        arg0: numpy.typing.NDArray,
        arg1: numpy.typing.NDArray,
        arg2: numpy.typing.NDArray,
        arg3: numpy.typing.NDArray,
    ) -> None: ...
    def clean(self) -> numpy.typing.NDArray: ...
    def set_min_consistent_views(self, arg0: int) -> None: ...
    def set_same_depth_threshold(self, arg0: float) -> None: ...


class DepthmapEstimator:
    def __init__(self) -> None: ...

    def add_view(
        self,
        arg0: numpy.typing.NDArray,
        arg1: numpy.typing.NDArray,
        arg2: numpy.typing.NDArray,
        arg3: numpy.typing.NDArray,
        arg4: numpy.typing.NDArray,
    ) -> None: ...
    def compute_brute_force(self) -> list: ...
    def compute_patch_match(self) -> list: ...
    def compute_patch_match_sample(self) -> list: ...
    def set_depth_range(self, arg0: float, arg1: float, arg2: int) -> None: ...
    def set_min_patch_sd(self, arg0: float) -> None: ...
    def set_patch_size(self, arg0: int) -> None: ...
    def set_patchmatch_iterations(self, arg0: int) -> None: ...


class DepthmapPruner:
    def __init__(self) -> None: ...

    def add_view(
        self,
        arg0: numpy.typing.NDArray,
        arg1: numpy.typing.NDArray,
        arg2: numpy.typing.NDArray,
        arg3: numpy.typing.NDArray,
        arg4: numpy.typing.NDArray,
        arg5: numpy.typing.NDArray,
        arg6: numpy.typing.NDArray,
    ) -> None: ...
    def prune(self) -> list: ...
    def set_same_depth_threshold(self, arg0: float) -> None: ...


class DepthmapFuser:
    def __init__(self) -> None: ...

    def add_view(
        self,
        K: numpy.typing.NDArray,
        R: numpy.typing.NDArray,
        t: numpy.typing.NDArray,
        depth: numpy.typing.NDArray,
        normal: numpy.typing.NDArray,
        color: numpy.typing.NDArray,
        mask: numpy.typing.NDArray,
        neighbor_ids: numpy.typing.NDArray,
        primary: bool = True,
    ) -> None: ...
    def fuse(self) -> list: ...
    def set_border_margin(self, arg0: int) -> None: ...
    def set_max_depth_error(self, arg0: float) -> None: ...
    def set_max_normal_error(self, arg0: float) -> None: ...
    def set_max_reproj_error(self, arg0: float) -> None: ...
    def set_min_num_consistent(self, arg0: int) -> None: ...
    def set_num_threads(self, arg0: int) -> None: ...
    def set_sor_params(self, arg0: int, arg1: float) -> None: ...


class OpenMVSExporter:
    def __init__(self) -> None: ...

    def add_camera(
        self, arg0: str, arg1: numpy.typing.NDArray, arg2: int, arg3: int
    ) -> None: ...
    def add_point(self, arg0: numpy.typing.NDArray, arg1: list) -> None: ...

    def add_shot(
        self,
        arg0: str,
        arg1: str,
        arg2: str,
        arg3: str,
        arg4: numpy.typing.NDArray,
        arg5: numpy.typing.NDArray,
    ) -> None: ...
    def export(self, arg0: str) -> None: ...


class StaticExtensionLoader:
    pass


class GPUDepthmapCleaner:
    def __init__(self) -> None: ...
    def set_same_depth_threshold(self, arg0: float) -> None: ...
    def set_min_consistent_views(self, arg0: int) -> None: ...
    def set_carving_threshold(self, arg0: float) -> None: ...
    def set_max_carved_views(self, arg0: int) -> None: ...
    def set_device(self, arg0: int) -> None: ...

    def add_view(
        self,
        arg0: numpy.typing.NDArray,
        arg1: numpy.typing.NDArray,
        arg2: numpy.typing.NDArray,
        arg3: numpy.typing.NDArray,
    ) -> None: ...
    def clean(self, arg0: int,
              arg1: numpy.typing.NDArray) -> numpy.typing.NDArray: ...

    def clear(self) -> None: ...
    @staticmethod
    def is_available() -> bool: ...


class DSMRasterizer:
    def __init__(self) -> None: ...
    def set_gsd(self, arg0: float) -> None: ...

    def set_bbox(
        self,
        min_xy: numpy.typing.NDArray,
        max_xy: numpy.typing.NDArray,
    ) -> None: ...
    def set_device(self, arg0: int) -> None: ...
    def set_outlier_threshold(self, arg0: float) -> None: ...
    def set_min_count(self, arg0: int) -> None: ...
    def set_z_bias(self, arg0: float) -> None: ...

    def set_bilateral(
        self,
        enabled: bool,
        radius: int,
        range_sigma: float,
    ) -> None: ...
    def begin(self) -> None: ...

    def scatter(
        self,
        K: numpy.typing.NDArray,
        R: numpy.typing.NDArray,
        t: numpy.typing.NDArray,
        depth: numpy.typing.NDArray,
        normal: numpy.typing.NDArray,
        confidence: numpy.typing.NDArray,
    ) -> None: ...
    def begin_pass2(self) -> None: ...
    def finish(self) -> numpy.typing.NDArray: ...

    def scatter_cpu(
        self,
        K: numpy.typing.NDArray,
        R: numpy.typing.NDArray,
        t: numpy.typing.NDArray,
        depth: numpy.typing.NDArray,
        normal: numpy.typing.NDArray,
        confidence: numpy.typing.NDArray,
    ) -> None: ...
    def finish_percentile(self, percentile: float) -> numpy.typing.NDArray: ...
    def set_reference_z(self, ref_z: numpy.typing.NDArray) -> None: ...
    @staticmethod
    def is_available() -> bool: ...
