name: Conda

on: [push, pull_request]

jobs:

  build-test:
    name: Build conda environment and run tests

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            lockfile: conda-linux-64.lock
          - os: ubuntu-22.04
            lockfile: conda-linux-64.lock
          - os: macos-latest
            lockfile: conda-osx-arm64.lock

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ${{ matrix.lockfile }}
          activate-environment: opensfm

      - name: Build OpenSfM
        shell: bash -l {0}
        run: pip install -e .[test]

      - name: Run C++ tests
        shell: bash -l {0}
        run: cd build && ctest

      - name: Run Python tests
        shell: bash -l {0}
        run: export LD_PRELOAD=$CONDA_PREFIX/lib/libtcmalloc.so && python -m pytest
